# Generated by Django 2.0.3 on 2018-05-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0064_productvariant_handle_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_needupload',
            field=models.BooleanField(default=False, verbose_name='is_needupload')
        ),
        
        migrations.AddField(
            model_name='product',
            name='upload_file',
            field=models.FileField(verbose_name='upload_file', null=True, upload_to='saved_files/%Y%m%d')
        ),        
    ]
