# Generated by Django 2.0.3 on 2018-09-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0065_add_to_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_needupload',
        ),
        migrations.RemoveField(
            model_name='product',
            name='upload_file',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='download_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='exe_name',
            field=models.CharField(default='exe.py', max_length=255),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_download_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_need_download',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_need_upload',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_upload_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='upload_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='work_base',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
